spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///E:/Cardy/configserver/
server.port=8888

# Ép t?t hoàn toàn các bean liên quan ??n Eureka/Discovery
spring.cloud.discovery.enabled=false
eureka.client.enabled=false
eureka.registration.enabled=false