# C?u hình ??nh tuy?n cho Gateway
spring.cloud.gateway.routes[0].id=product-service-route
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**